name: Dependabot auto-merge
on: pull_request_target

jobs:
  dependabot:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1.10.1
        with:
          app-id: ${{ secrets.FETCH_METADATA_ACTION_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.FETCH_METADATA_ACTION_AUTOMATION_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Auto-merge
        run: gh pr merge --auto --merge '${{ github.event.pull_request.html_url }}'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
